name: thrive_carbon_first_project
version: 1.0
profile: thrive_carbon_project  # ✅ must match profile name in ~/.dbt/profiles.yml

config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  thrive_carbon_project:
    +materialized: view